version: "3.9"

services:
  web:
    image: ghcr.io/<ORG_OR_USER>/flask-app:latest
    container_name: flask-app
    restart: always
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./database:/app/database
