services:
  web:
    image: ghcr.io/alaeddine257/flask-app:latest
    container_name: flask-app
    restart: always
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./database:/app/database
